apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: listener
    name: listener
  spec:
    replicas: 1
    selector:
      app: listener
      deploymentconfig: listener
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: listener
          deploymentconfig: listener
      spec:
        containers:
        - name: listener 
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          securityContext:
             privileged: false
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        containerNames:
        - listener
        from:
          kind: ImageStreamTag
          name: listener:latest
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: listener
      deploymentconfig: listener
    name: listener
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: listener
      deploymentconfig: listener
  status:
    loadBalancer: {}
